### PR TITLE
	why do we need to switch a new Fragment when we are already here?

### PR DESCRIPTION
**Pull request by notly**

### CODE REVIEW

**Comment by PeratX** [comment]
The item can be selected when it has been selected??

**Comment by PeratX** [comment]
And, please do one thing in one pull request. Thank you very much!

**Comment by notly** [comment]
ok, next time.. 🔢 
The Question: yes, the item can be selected when it has already selected!

**Comment by PeratX** [comment]
Oh! May be we can ```switchFragment(xxxFragment.class)``` and let the function check whether the currentFragment is it.

**Pull request closed without merging**
