### PR TITLE
 Logger uses perfs to log; make sure prefs is not null beforce log something

### PR DESCRIPTION
**Pull request by notly**
Logger uses perfs to log; make sure prefs is not null beforce log something

### CODE REVIEW

**Comment by PeratX** [comment]
Still WIP?

**Comment by notly** [comment]
when the app first launches,  will use Logger.warning func
warning => send => checkBufferSize => getLogSizeLimit

```
private static int getLogSizeLimit() {
        return Integer.parseInt(Daedalus.getPrefs().getString("settings_log_size", "10000"));
    }
```

**Comment by PeratX** [comment]
Then why not make initData at the head of the starting sequence.

**Comment by PeratX** [comment]
Thank you!

**Pull request merged**
